###
POST http://localhost:3000/auth/login
Content-type: application/json

{
    "email": "partner1@user.com",
    "password": "secret"
}

###
POST http://localhost:3000/partners/register
Content-type: application/json

{
    "name": "Partner 1",
    "email": "partner1@user.com",
    "password": "secret",
    "company_name": "Company 1"
}

###
POST http://localhost:3000/customers/register
Content-type: application/json

{
    "name": "Costumer 1",
    "email": "partner1@user.com",
    "password": "secret",
    "adress": "Street 1",
    "phone": "123456789"
}

###
POST http://localhost:3000/partners/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJwYXJ0bmVyMUB1c2VyLmNvbSIsImlhdCI6MTc0ODYxNDA5NywiZXhwIjoxNzQ4NjIxMjk3fQ.ILqePnXrY4Xy-WK0sEJgn56AiPHvunMrS1P9e8_p66g

{
    "name": "Evento test 1",
    "description": "descrição do evento",
    "date": "2025-01-01T00:00:00",
    "location": "Rua X, bairro etc"
}

###
GET http://localhost:3000/partners/events

###
GET http://localhost:3000/partners/events/:eventId

{
    "eventId": 1
}

###
POST http://localhost:3000/events
Content-type: application/json

{
    "name": "Event 1",
    "description": "Description 1",
    "date": "2023-10-01T00:00:00Z",
    "location": "Location 1"
}

###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/1